# Generated by Django 4.1.3 on 2022-11-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notemodel',
            options={'ordering': ['createdAt']},
        ),
    ]
