# Generated by Django 4.1.3 on 2022-11-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_api', '0002_improved_notes_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='createdAt',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
